package parse

import (
	"testing"

	"github.com/cyprob/cyprob/pkg/engine"
	scanpkg "github.com/cyprob/cyprob/pkg/modules/scan"
)

func TestDetectHTTPIdentityHint_ProxyResponseIgnored(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.10",
		Port:          443,
		ProbeHost:     "example.com",
		ResponseClass: bannerResponseClassProxyOnly,
		ProxyResponse: true,
		Banner:        "HTTP/1.1 502 Bad Gateway\r\nVia: HTTP/1.1 forward.http.proxy:3128\r\n\r\ngenerated by forward proxy",
	})
	if len(signals) != 0 {
		t.Fatalf("expected no signals for proxy response, got %+v", signals)
	}
	if reason != httpIdentitySkipProxyOnly {
		t.Fatalf("expected proxy_only reason, got %q", reason)
	}
}

func TestDetectHTTPIdentitySignals_GitHubOriginResponse(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "140.82.121.4",
		Port:          443,
		ProbeHost:     "github.com",
		SNIServerName: "github.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 200 OK\r\nSet-Cookie: _octo=GH1.1.1234\r\nContent-Type: text/html\r\n\r\n" +
			"<html><head><title>GitHub · Build software better, together</title></head><body>GitHub</body></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubHost) || !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubCookie) {
		t.Fatalf("expected github signals, got %+v", signals)
	}
	if signalConfidence(signals, httpIdentitySignalGitHubHost) != httpIdentityConfidenceGitHub {
		t.Fatalf("expected confidence %.2f, got %.2f", httpIdentityConfidenceGitHub, signalConfidence(signals, httpIdentitySignalGitHubHost))
	}
}

func TestDetectHTTPIdentitySignals_SmarterMailOriginResponse(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "185.67.204.138",
		Port:          443,
		ProbeHost:     "mail.netkedi.com",
		SNIServerName: "mail.netkedi.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 302 Found\r\nLocation: /interface/root\r\nX-Powered-By: ASP.NET\r\n\r\n" +
			"<html><head><title>SmarterMail</title></head></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalSmarterMailRoute) || !hasHTTPIdentitySignal(signals, httpIdentitySignalSmarterMailTitle) {
		t.Fatalf("expected smartermail signals, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_GenericServerIgnored(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.30",
		Port:          443,
		ProbeHost:     "www.example.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner:        "HTTP/1.1 200 OK\r\nServer: nginx/1.27.0\r\n\r\n<html><title>Welcome</title></html>",
	})
	if len(signals) != 0 {
		t.Fatalf("expected no signals for generic server, got %+v", signals)
	}
	if reason != httpIdentitySkipNoSignature {
		t.Fatalf("expected no_signature reason, got %q", reason)
	}
}

func TestDetectHTTPIdentitySignals_XPoweredByAndServerStaySignalsOnly(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.40",
		Port:          443,
		ProbeHost:     "www.example.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner:        "HTTP/1.1 200 OK\r\nServer: Microsoft-IIS/10.0\r\nX-Powered-By: ASP.NET\r\n\r\n<html><title>Welcome</title></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, "server:microsoft-iis") || !hasHTTPIdentitySignal(signals, "x-powered-by:asp.net") {
		t.Fatalf("expected header tokens only, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_UsesOriginEvidenceOnly(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "140.82.121.4",
		Port:          443,
		ProbeHost:     "github.com",
		ResponseClass: bannerResponseClassProxyOnly,
		ProxyResponse: true,
		Evidence: []engine.ProbeObservation{
			{
				ProbeID:       "http-get",
				ResponseClass: bannerResponseClassProxyOnly,
				ProxyResponse: true,
				Response:      "HTTP/1.1 502 Bad Gateway\r\nVia: HTTP/1.1 forward.http.proxy:3128\r\n\r\n",
			},
			{
				ProbeID:       "https-get",
				ResponseClass: bannerResponseClassOrigin,
				Response:      "HTTP/1.1 200 OK\r\nSet-Cookie: _octo=GH1.1.1234\r\n\r\n<html><title>GitHub</title></html>",
			},
		},
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubCookie) {
		t.Fatalf("expected origin evidence signal, got %+v", signals)
	}
}

func hasHTTPIdentitySignal(signals []httpIdentitySignal, want string) bool {
	return signalConfidence(signals, want) > 0
}

func signalConfidence(signals []httpIdentitySignal, want string) float64 {
	for _, signal := range signals {
		if signal.Token == want {
			return signal.Confidence
		}
	}
	return 0
}
