package parse

import (
	"testing"

	"github.com/cyprob/cyprob/pkg/engine"
	scanpkg "github.com/cyprob/cyprob/pkg/modules/scan"
)

func TestDetectHTTPIdentityHint_ProxyResponseIgnored(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.10",
		Port:          443,
		ProbeHost:     "example.com",
		ResponseClass: bannerResponseClassProxyOnly,
		ProxyResponse: true,
		Banner:        "HTTP/1.1 502 Bad Gateway\r\nVia: HTTP/1.1 forward.http.proxy:3128\r\n\r\ngenerated by forward proxy",
	})
	if len(signals) != 0 {
		t.Fatalf("expected no signals for proxy response, got %+v", signals)
	}
	if reason != httpIdentitySkipProxyOnly {
		t.Fatalf("expected proxy_only reason, got %q", reason)
	}
}

func TestDetectHTTPIdentitySignals_GitHubOriginResponse(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "140.82.121.4",
		Port:          443,
		ProbeHost:     "github.com",
		SNIServerName: "github.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 200 OK\r\nSet-Cookie: _octo=GH1.1.1234\r\nContent-Type: text/html\r\n\r\n" +
			"<html><head><title>GitHub · Build software better, together</title></head><body>GitHub</body></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubHost) || !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubCookie) {
		t.Fatalf("expected github signals, got %+v", signals)
	}
	if signalConfidence(signals, httpIdentitySignalGitHubHost) != httpIdentityConfidenceGitHub {
		t.Fatalf("expected confidence %.2f, got %.2f", httpIdentityConfidenceGitHub, signalConfidence(signals, httpIdentitySignalGitHubHost))
	}
}

func TestDetectHTTPIdentitySignals_SmarterMailOriginResponse(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "185.67.204.138",
		Port:          443,
		ProbeHost:     "mail.netkedi.com",
		SNIServerName: "mail.netkedi.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 302 Found\r\nLocation: /interface/root\r\nX-Powered-By: ASP.NET\r\n\r\n" +
			"<html><head><title>SmarterMail</title></head></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalSmarterMailRoute) || !hasHTTPIdentitySignal(signals, httpIdentitySignalSmarterMailTitle) {
		t.Fatalf("expected smartermail signals, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_CPanelOriginResponse(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "95.173.184.54",
		Port:          2082,
		ProbeHost:     "95.173.184.54",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 200 OK\r\nSet-Cookie: cprelogin=no; path=/; port=2082\r\n\r\n" +
			`<html><head><title>cPanel Login</title></head><body>` +
			`<link href="/cPanel_magic_revision_1677093441/unprotected/cpanel/style.css">` +
			`<form id="login_form" action="/login/" method="post">` +
			`<input name="user"><input name="pass"></form></body></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelMagic) ||
		!hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelLoginForm) ||
		!hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelCookie) {
		t.Fatalf("expected cPanel signals, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_CPanelPortRedirect(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "188.34.185.206",
		Port:          2082,
		ProbeHost:     "188.34.185.206",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 301 Moved\r\n" +
			"Location: https://portal.example.test:2083/\r\n" +
			"Content-Type: text/html; charset=\"utf-8\"\r\n\r\n" +
			`<html><head><META HTTP-EQUIV="refresh" CONTENT="2;URL=https://portal.example.test:2083/"></head></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelPortRedirect) {
		t.Fatalf("expected cPanel port redirect signal, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_CPanelPortRedirectWithoutTrailingSlash(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "188.34.185.206",
		Port:          2083,
		ProbeHost:     "188.34.185.206",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 301 Moved\r\n" +
			"Location: https://portal.example.test:2083\r\n" +
			"Content-Type: text/html; charset=\"utf-8\"\r\n\r\n" +
			`<html><head><META HTTP-EQUIV="refresh" CONTENT="2;URL=https://portal.example.test:2083"></head></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelPortRedirect) {
		t.Fatalf("expected cPanel port redirect signal, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_WHMPortRedirectWithoutTrailingSlash(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "188.34.185.206",
		Port:          2087,
		ProbeHost:     "188.34.185.206",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 301 Moved\r\n" +
			"Location: https://portal.example.test:2087\r\n" +
			"Content-Type: text/html; charset=\"utf-8\"\r\n\r\n" +
			`<html><head><META HTTP-EQUIV="refresh" CONTENT="2;URL=https://portal.example.test:2087"></head></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalWHMPortRedirect) {
		t.Fatalf("expected WHM port redirect signal, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_CPanelWebmailPortRedirectWithoutTrailingSlash(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "188.34.185.206",
		Port:          2096,
		ProbeHost:     "188.34.185.206",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 301 Moved\r\n" +
			"Location: https://portal.example.test:2096\r\n" +
			"Content-Type: text/html; charset=\"utf-8\"\r\n\r\n" +
			`<html><head><META HTTP-EQUIV="refresh" CONTENT="2;URL=https://portal.example.test:2096"></head></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelWebmailRedirect) {
		t.Fatalf("expected cPanel webmail port redirect signal, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_WHMSignals(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "95.173.184.54",
		Port:          2086,
		ProbeHost:     "95.173.184.54",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 200 OK\r\nSet-Cookie: whostmgrrelogin=no; path=/; port=2086\r\n" +
			"Set-Cookie: whostmgrsession=abc; path=/; port=2086\r\n\r\n" +
			`<html><head><title>WHM Login</title></head><body>` +
			`<link href="/cPanel_magic_revision_1677093441/unprotected/cpanel/style.css">` +
			`</body></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalWHMCookie) ||
		!hasHTTPIdentitySignal(signals, httpIdentitySignalWHMTitle) {
		t.Fatalf("expected WHM signals, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_CPanelWebmailSignals(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "95.173.184.54",
		Port:          2095,
		ProbeHost:     "95.173.184.54",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 200 OK\r\nSet-Cookie: webmailrelogin=no; path=/; port=2095\r\n" +
			"Set-Cookie: webmailsession=abc; path=/; port=2095\r\n\r\n" +
			`<html><head><title>Webmail Login</title></head><body>` +
			`<link href="/cPanel_magic_revision_1677093441/unprotected/cpanel/style.css">` +
			`</body></html>`,
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelWebmailCookie) ||
		!hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelWebmailTitle) {
		t.Fatalf("expected cPanel webmail signals, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_ControlWebPanelRedirectDoesNotBecomeCPanel(t *testing.T) {
	t.Parallel()

	signals, _ := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "78.47.198.245",
		Port:          2082,
		ProbeHost:     "78.47.198.245",
		ResponseClass: bannerResponseClassOrigin,
		Banner: "HTTP/1.1 301 Moved Permanently\r\n" +
			"Server: cwpsrv\r\n" +
			"Location: https://78.47.198.245:2083/\r\n\r\n" +
			`<html><body><link href="/login/cwp_theme/original/css/style.css"></body></html>`,
	})
	if hasHTTPIdentitySignal(signals, httpIdentitySignalCPanelPortRedirect) {
		t.Fatalf("did not expect cPanel signal for CWP redirect, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_GenericServerIgnored(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.30",
		Port:          443,
		ProbeHost:     "www.example.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner:        "HTTP/1.1 200 OK\r\nServer: nginx/1.27.0\r\n\r\n<html><title>Welcome</title></html>",
	})
	if len(signals) != 0 {
		t.Fatalf("expected no signals for generic server, got %+v", signals)
	}
	if reason != httpIdentitySkipNoSignature {
		t.Fatalf("expected no_signature reason, got %q", reason)
	}
}

func TestDetectHTTPIdentitySignals_XPoweredByAndServerStaySignalsOnly(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "198.51.100.40",
		Port:          443,
		ProbeHost:     "www.example.com",
		ResponseClass: bannerResponseClassOrigin,
		Banner:        "HTTP/1.1 200 OK\r\nServer: Microsoft-IIS/10.0\r\nX-Powered-By: ASP.NET\r\n\r\n<html><title>Welcome</title></html>",
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, "server:microsoft-iis") || !hasHTTPIdentitySignal(signals, "x-powered-by:asp.net") {
		t.Fatalf("expected header tokens only, got %+v", signals)
	}
}

func TestDetectHTTPIdentitySignals_UsesOriginEvidenceOnly(t *testing.T) {
	t.Parallel()

	signals, reason := detectHTTPIdentitySignals(scanpkg.BannerGrabResult{
		IP:            "140.82.121.4",
		Port:          443,
		ProbeHost:     "github.com",
		ResponseClass: bannerResponseClassProxyOnly,
		ProxyResponse: true,
		Evidence: []engine.ProbeObservation{
			{
				ProbeID:       "http-get",
				ResponseClass: bannerResponseClassProxyOnly,
				ProxyResponse: true,
				Response:      "HTTP/1.1 502 Bad Gateway\r\nVia: HTTP/1.1 forward.http.proxy:3128\r\n\r\n",
			},
			{
				ProbeID:       "https-get",
				ResponseClass: bannerResponseClassOrigin,
				Response:      "HTTP/1.1 200 OK\r\nSet-Cookie: _octo=GH1.1.1234\r\n\r\n<html><title>GitHub</title></html>",
			},
		},
	})
	if reason != "" {
		t.Fatalf("expected no skip reason, got %q", reason)
	}
	if !hasHTTPIdentitySignal(signals, httpIdentitySignalGitHubCookie) {
		t.Fatalf("expected origin evidence signal, got %+v", signals)
	}
}

func hasHTTPIdentitySignal(signals []httpIdentitySignal, want string) bool {
	return signalConfidence(signals, want) > 0
}

func signalConfidence(signals []httpIdentitySignal, want string) float64 {
	for _, signal := range signals {
		if signal.Token == want {
			return signal.Confidence
		}
	}
	return 0
}
