//go:build ignore

// Command gen_tls_cipher_suites turns IANA's TLS cipher suite registry into a
// Go table the raw-ClientHello enumerator can offer from.
//
// The enumerator exists because crypto/tls implements 25 of the registry's
// suites and a scanner that can only ask about 25 cannot answer "which suites
// does this server support" (cyprob#294). A hand-built ClientHello can offer an
// arbitrary 2-byte ID, so the candidate list comes from the registry rather
// than from what our own TLS stack happens to implement.
//
// Usage:
//
//	go run tools/gen_tls_cipher_suites.go > pkg/modules/scan/tls_cipher_suite_registry.go
//	go run tools/gen_tls_cipher_suites.go -csv /path/to/tls-parameters-4.csv > ...
//
// Without -csv the registry is fetched from IANA. The output records where the
// table came from and when, because a stale table is a silent naming
// regression: an unnamed suite renders as bare hex, and a bare hex string in a
// field a plugin pattern matches against reports zero and reads as clean.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const registryURL = "https://www.iana.org/assignments/tls-parameters/tls-parameters-4.csv"

var valuePattern = regexp.MustCompile(`^0x([0-9A-Fa-f]{2}),0x([0-9A-Fa-f]{2})$`)

type suite struct {
	id   uint16
	name string
}

func main() {
	csvPath := flag.String("csv", "", "read the registry from this file instead of fetching it")
	flag.Parse()

	rows, source, err := loadRegistry(*csvPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen_tls_cipher_suites:", err)
		os.Exit(1)
	}

	named, skipped := classify(rows)
	sort.Slice(named, func(i, j int) bool { return named[i].id < named[j].id })

	var legacy, tls13 []suite
	for _, s := range named {
		switch {
		case s.id>>8 == 0x13:
			tls13 = append(tls13, s)
		case s.id == 0x0000, s.id == 0x00FF, s.id == 0x5600:
			// Named so a server that selects one can be reported by name, but
			// never offered: 0x0000 is the null placeholder, and the two SCSVs
			// are signals rather than suites.
		default:
			legacy = append(legacy, s)
		}
	}

	emit(os.Stdout, source, len(rows), named, legacy, tls13, skipped)
}

func loadRegistry(path string) ([][]string, string, error) {
	if path != "" {
		f, err := os.Open(path)
		if err != nil {
			return nil, "", err
		}
		defer func() { _ = f.Close() }()
		rows, err := csv.NewReader(f).ReadAll()
		return rows, path, err
	}

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(registryURL)
	if err != nil {
		return nil, "", err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, "", fmt.Errorf("registry returned %s", resp.Status)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, "", err
	}
	rows, err := csv.NewReader(strings.NewReader(string(body))).ReadAll()
	return rows, registryURL, err
}

// classify keeps the rows that name a single assigned suite and counts the rest.
// Unassigned, Reserved (which is where the GREASE values live) and range rows
// are not suites anything should be offered or named by.
func classify(rows [][]string) (named []suite, skipped map[string]int) {
	skipped = map[string]int{}
	for i, row := range rows {
		if i == 0 || len(row) < 2 {
			continue
		}
		value, description := strings.TrimSpace(row[0]), strings.TrimSpace(row[1])
		match := valuePattern.FindStringSubmatch(value)
		if match == nil {
			skipped["range_or_malformed_value"]++
			continue
		}
		lower := strings.ToLower(description)
		switch {
		case strings.HasPrefix(lower, "unassigned"):
			skipped["unassigned"]++
			continue
		case strings.HasPrefix(lower, "reserved"):
			skipped["reserved"]++
			continue
		case description == "":
			skipped["empty_description"]++
			continue
		}
		hi, _ := strconv.ParseUint(match[1], 16, 8)
		lo, _ := strconv.ParseUint(match[2], 16, 8)
		id := uint16(hi)<<8 | uint16(lo)
		if isGREASE(id) {
			skipped["grease"]++
			continue
		}
		named = append(named, suite{id: id, name: description})
	}
	return named, skipped
}

// isGREASE matches RFC 8701's reserved values. They exist to be ignored, so a
// scanner neither offers them nor names them.
func isGREASE(id uint16) bool {
	return id&0x0F0F == 0x0A0A && id&0xFF == id>>8
}

func emit(w io.Writer, source string, rowCount int, named, legacy, tls13 []suite, skipped map[string]int) {
	reasons := make([]string, 0, len(skipped))
	for reason := range skipped {
		reasons = append(reasons, reason)
	}
	sort.Strings(reasons)
	counts := make([]string, 0, len(reasons))
	for _, reason := range reasons {
		counts = append(counts, fmt.Sprintf("%s=%d", reason, skipped[reason]))
	}

	fmt.Fprintf(w, "// Code generated by tools/gen_tls_cipher_suites.go; DO NOT EDIT.\n//\n")
	fmt.Fprintf(w, "// Source:    %s\n", source)
	fmt.Fprintf(w, "// Retrieved: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(w, "// Registry:  %d rows, %d named suites (skipped: %s)\n//\n",
		rowCount-1, len(named), strings.Join(counts, ", "))
	fmt.Fprintf(w, "// Regenerate with:\n//\n//\tgo run tools/gen_tls_cipher_suites.go > pkg/modules/scan/tls_cipher_suite_registry.go\n\n")
	fmt.Fprintf(w, "package scan\n\n")

	fmt.Fprintf(w, "// tlsRegistrySuiteNames names every assigned suite, including the two SCSVs\n")
	fmt.Fprintf(w, "// and the null placeholder that are never offered -- a server that selects one\n")
	fmt.Fprintf(w, "// of those is reporting a protocol violation, and it should be reported by name.\n")
	fmt.Fprintf(w, "var tlsRegistrySuiteNames = map[uint16]string{\n")
	for _, s := range named {
		fmt.Fprintf(w, "\t0x%04X: %q,\n", s.id, s.name)
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// tlsRegistryLegacySuiteIDs is the offer for a walk pinned below TLS 1.3,\n")
	fmt.Fprintf(w, "// ascending so the offer is reproducible and auditable. TLS 1.3's suites are a\n")
	fmt.Fprintf(w, "// disjoint namespace and are not in it.\n")
	writeIDs(w, "tlsRegistryLegacySuiteIDs", legacy)

	fmt.Fprintf(w, "\n// tlsRegistryTLS13SuiteIDs is the offer for a walk pinned to TLS 1.3.\n")
	writeIDs(w, "tlsRegistryTLS13SuiteIDs", tls13)
}

func writeIDs(w io.Writer, name string, suites []suite) {
	fmt.Fprintf(w, "var %s = []uint16{\n", name)
	for _, s := range suites {
		fmt.Fprintf(w, "\t0x%04X, // %s\n", s.id, s.name)
	}
	fmt.Fprintf(w, "}\n")
}
